///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("0157b8fd-e85d-4a22-8604-0c54d2f5fa48")]
    public partial class MyTest2Repository : RepoGenBaseFolder
    {
        static MyTest2Repository instance = new MyTest2Repository();
        MyTest2RepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyTest2RepositoryFolders.HọcLiệuSachMềmAppFolder _họcliệusachmềm;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest2Repository element repository.
        /// </summary>
        [RepositoryFolder("0157b8fd-e85d-4a22-8604-0c54d2f5fa48")]
        public static MyTest2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest2Repository() 
            : base("MyTest2Repository", "/", null, 0, false, "0157b8fd-e85d-4a22-8604-0c54d2f5fa48", ".\\RepositoryImages\\MyTest2Repository0157b8fd.rximgres")
        {
            _applicationundertest = new MyTest2RepositoryFolders.ApplicationUnderTestAppFolder(this);
            _họcliệusachmềm = new MyTest2RepositoryFolders.HọcLiệuSachMềmAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("0157b8fd-e85d-4a22-8604-0c54d2f5fa48")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("cd94099e-53c2-4d83-a7a7-dab6fea2f718")]
        public virtual MyTest2RepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The HọcLiệuSachMềm folder.
        /// </summary>
        [RepositoryFolder("9df6646b-d1c5-486e-8d66-9b4fb2f8153c")]
        public virtual MyTest2RepositoryFolders.HọcLiệuSachMềmAppFolder HọcLiệuSachMềm
        {
            get { return _họcliệusachmềm; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest2RepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("cd94099e-53c2-4d83-a7a7-dab6fea2f718")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, true, "cd94099e-53c2-4d83-a7a7-dab6fea2f718", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cd94099e-53c2-4d83-a7a7-dab6fea2f718")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cd94099e-53c2-4d83-a7a7-dab6fea2f718")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The HọcLiệuSachMềmAppFolder folder.
        /// </summary>
        [RepositoryFolder("9df6646b-d1c5-486e-8d66-9b4fb2f8153c")]
        public partial class HọcLiệuSachMềmAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _submitInfo;

            /// <summary>
            /// Creates a new HọcLiệuSachMềm  folder.
            /// </summary>
            public HọcLiệuSachMềmAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HọcLiệuSachMềm", "/dom[@caption='Học liệu - Sách Mềm' and @page='Th%C6%B0_m%E1%BB%A5c_c%E1%BB%A7a_t%C3%B4i-5c6d2a760966f254d79b73c9']", parentFolder, 30000, null, false, "9df6646b-d1c5-486e-8d66-9b4fb2f8153c", "")
            {
                _submitInfo = new RepoItemInfo(this, "Submit", ".//div[#'createAssignmentModal']//form[@action='https://hoclieu.sachmem.vn/folder/Th%C6%B0_m%E1%BB%A5c_c%E1%BB%A7a_t%C3%B4i-5c6d2a760966f254d79b73c9']/?/?/input[@type='submit']", 30000, null, "62a54430-9423-4328-bf85-f38f4be3149d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9df6646b-d1c5-486e-8d66-9b4fb2f8153c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9df6646b-d1c5-486e-8d66-9b4fb2f8153c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("62a54430-9423-4328-bf85-f38f4be3149d")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("62a54430-9423-4328-bf85-f38f4be3149d")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
